### ISSUE TITLE
libpajeutils is back?

### ISSUE THREAD

**Issue by mquinson** [schnorr/pajeng#21]
Hello,

it seems that version 1.3.2 reintroduces the libpajeutils library. Is it really useful? This complicates the packaging, and I don't see no advantage: is there really a situation where libpaje could be installed without libpajeutils (or the contrary) ? If not, I think that it'd be easier for the users to merge the libs again.

Thanks for your time,

**Comment by schnorr** [comment]
Hello, 
The libpajeutils has PajeThreadReader class, which is solely used by viva to read paje trace files. I see two options here:
- Move its implementation to the viva package, since it depends on Qt. Doing that, we can free pajeng from qt dependencies (since the pajeng graphical interface is deprecated in favor of R+ggplot2).
- Integrate PajeThreadReader into the libpaje, like you said.
What do you think it is the best? I'd favor the first option because I like to free pajeng of Qt.

**Comment by mquinson** [comment]
Hello,

the first solution is simpler and thus much more appealing to me. It
require a release of both software, but once it's done, this mess is
definitely sorted out.

Thanks for your time,

**Comment by mquinson** [comment]
Hello,

did you find the time to progress on this issue? It's blocking for the integration of Viva in Debian (and Ubuntu), and that's definitely something I'd like to sort before the freeze of the next Debian version (which should occur by the end of October).

Thanks for your time,
Mt

**Comment by schnorr** [comment]
Hello, now there is no dependency in qt at all for pajeng framework (I've removed the pajeng graphical tool source code which is deprecated by default and not included in latest releases for quite a time). The tag 1.3.4 in this repository marks these changes. Viva tag to consider this change is 1.2. Let me know if something breaks up in your side.

**Comment by mquinson** [comment]
Ok, paje hit the debian servers yesterday, and I hope to build viva tonight. Debian packaging is making fool of me, but I'll find the way.

**Comment by mquinson** [comment]
Viva is uploaded. It should be good now. 

COOL, I HAVE VIVA working on my box!
F34R the upcoming bug reports when I use it :)
